// 3474. Lexicographically Smallest Generated String
// Solved
// Hard
// Topics
// premium lock icon
// Companies
// Hint
// You are given two strings, str1 and str2, of lengths n and m, respectively.

// A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:

// If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
// If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
// Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".

 

// Example 1:

// Input: str1 = "TFTF", str2 = "ab"

// Output: "ababa"

// Explanation:

// The table below represents the string "ababa"
// Index	T/F	Substring of length m
// 0	'T'	"ab"
// 1	'F'	"ba"
// 2	'T'	"ab"
// 3	'F'	"ba"
// The strings "ababa" and "ababb" can be generated by str1 and str2.

// Return "ababa" since it is the lexicographically smaller string.

// Example 2:

// Input: str1 = "TFTF", str2 = "abc"

// Output: ""

// Explanation:

// No string that satisfies the conditions can be generated.

// Example 3:

// Input: str1 = "F", str2 = "d"

// Output: "a"

 

// Constraints:

// 1 <= n == str1.length <= 104
// 1 <= m == str2.length <= 500
// str1 consists only of 'T' or 'F'.
// str2 consists only of lowercase English characters.

class Solution {
public:
    string generateString(string s, string t) {
        int n = s.size(), m = t.size();
        string ans(n + m - 1, '?'); 

       
        for (int i = 0; i < n; i++) {
            if (s[i] != 'T') {
                continue;
            }
         
            for (int j = 0; j < m; j++) {
                char v = ans[i + j];
                if (v != '?' && v != t[j]) {
                    return "";
                }
                ans[i + j] = t[j];
            }
        }

        string old_ans = ans;
        for (char& c : ans) {
            if (c == '?') {
                c = 'a';
            }
        }

  
        for (int i = 0; i < n; i++) {
            if (s[i] != 'F') {
                continue;
            }
           
            if (string(ans.begin() + i, ans.begin() + i + m) != t) {
                continue;
            }
            
            bool ok = false;
            for (int j = i + m - 1; j >= i; j--) {
                if (old_ans[j] == '?') { 
                    ans[j] = 'b';
                    ok = true;
                    break;
                }
            }
            if (!ok) {
                return "";
            }
        }

        return ans;
    }
};